services:
  db:
    image: postgres:17-alpine
    restart: always
    container_name: maru_db
    environment:
      POSTGRES_USER: maru
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
        context: ./bot
    restart: always
    container_name: maru_bot
    depends_on:
      - db

  web:
    build:
      context: ./web
    restart: always
    container_name: maru_web
    expose:
      - "5000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: always
    container_name: maru_nginx
    ports:
      - "80:80"
    volumes:
      - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

volumes:
  postgres_data: